version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_fastapi
    command: > 
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8008"
    volumes:
      - .:/code
    restart: on-failure
    ports:
      - "8008:8008"
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
  
volumes:
  postgres_data: